name: 'Simple CMake'
description: 'Configure, build and test a repository using CMake'
inputs:
  config:
    description: 'CMake configuration to use (Debug, Release, MinSizeRel, and RelWithDebInfo)'
    required: true
    default: 'Release'
  extra_configure_flags:
    description: 'Flags to be sent to CMake'
    required: false
outputs:
  build_dir:
    description: 'Build directory'
runs:
  using: 'node12'
  main: 'index.js'

