name: 'Simple CMake'
description: 'Configure, build and test a repository using CMake'
inputs:
  config:
    description: 'CMake configuration to use (Debug, Release, MinSizeRel, and RelWithDebInfo)'
    required: true
    default: 'Release'
  source_dir:
    description: 'Directory containing the root CMakeLists.txt - defaults to "."'
    required: false
  build_dir:
    description: 'Directory which will contain the output - defaults to "build"'
    required: false
  extra_configure_flags:
    description: 'Flags to be sent to CMake for configuring'
    required: false
  extra_build_flags:
    description: 'Flags to be sent to CMake for building'
    required: false
outputs:
  build_dir:
    description: 'Build directory'
runs:
  using: 'node12'
  main: 'index.js'

